### ISSUE TITLE
Support .gitlabels-style commit messages

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [boennemann/semantic-release#13]
This is a great idea.

So, in that vein, I want to make it work with the committing conventions I already use (I call them [git labels][].) How difficult would it to be to extend this with a parser for a format like the following:

    (tag tag tag) This commit introduces a message. With labels.

(Where `tag` is usually something like `new`, `fix`, `-` (minor), [or something else like that](https://github.com/ELLIOTTCABLE/Paws.js/blob/91f3c883b54ea585d4592b464a73603777db5b48/.gitlabels).)

A brief glance at your code looks like it's pretty tightly-coupled to the Angular's concept of a hard-coded *type* value, differentiated from anything else in the commit-message … whereas my style is a little more free-form. I'd like to define more nuanced heuristics for ‘this is breaking’ or ‘this is backwards-compatible’; is that in line with your project-goals?

   [git labels]: <https://github.com/ELLIOTTCABLE/.gitlabels>

**Comment by boennemann** [comment]
Hey @ELLIOTTCABLE,

thanks a lot for this issue. I'm totally up for this, but I'm super busy until mid/end next week.
I will get back to you then.
I hope you understand :)

Best,
Stephan

**Comment by boennemann** [comment]
Hey @ELLIOTTCABLE,

sorry for the super long delay. I'm currently working on this and while I'm not entirely finished yet, I will give you a glance at the new API.

You will be able to provide a function that `semantic-release` will call with an array of all commits since the last version was released. This function should then return the version type, like `major`, `minor`, `patch` or `null` for no release. 

```js
[{
  hash: '<a commit hash>',
  message: '<the commit message>'
}, {…}]
```

Is this something you could work with?

Best,
Stephan

**Comment by ELLIOTTCABLE** [comment]
Looks like a good plan to me. How do you plan on allowing, er, plugins / etc / whatever to be integrated into the `semantic-release` installation and usage pattern? (i.e. if I want to release a sem-release modification to support `.gitlabels`, how would you want me to do so?)

**Comment by boennemann** [comment]
My plan is to integrate a `release` section into the package.json.
You then provide a module name or path to require, with the signature I outlined above.

This is what it could look like for common analyzers that could be published on npm:
```json
"release": {
  "analyzer": "semantic-release-gitlabels"
}
```

And this is how you would define a file that just lies around your repository.
```json
"release: {
  "analyzer: "./build/release-analyzer"
}
```

Hope that makes sense ;)

**Comment by ELLIOTTCABLE** [comment]
Excited to see where it goes. I'll leave this issue subscribed; drop a note here when you push something I can play with. (=

**Comment by boennemann** [comment]
@ELLIOTTCABLE Have fun with it: https://github.com/boennemann/semantic-release/releases/tag/v3.1.0

Would love to get your feedback and maybe, ideally `semantic-release-gitlabels-analyzer` on npm :)

Next up: custom changelog

**Comment by ELLIOTTCABLE** [comment]
Curious about your thoughts on changelogs. (I'd make a new Issue, or contact you elsewhere, except this isn't really `semantic-release` specific, and I don't know your other presences).

I've been idly planning to put together some NIHey tooling to allow me to automatically generate changelogs like [this one](https://github.com/ELLIOTTCABLE/Paws.js/releases), which was primarily copy-pasted from commit logs, but manually beautified and very slightly changed (rather obviously, that particular approach is tightly coupled to gitlabeling, but you get the idea).

Are you planning to start working on new tooling for changelog generation and maintenance, or is that actually something you want to wrap *into* `semantic-release`?

**Comment by boennemann** [comment]
I've added a hook for changelog generation now: https://github.com/boennemann/semantic-release/wiki/release-note-generation

Maybe you could simply dump your commit messages into the log, and then go and edit them once they're published.

I hope that's what you're looking for :)
