### ISSUE TITLE
npm Could not pack error

### ISSUE THREAD

**Issue by tlvince** [boennemann/semantic-release#18]
(Sorry in advance for filing an issue on this; I couldn't find a better channel).

I'm trying to add semantic-release to https://github.com/angular-pouchdb/angular-pouchdb, but am running into:

`npm ERR! addLocalDirectory Could not pack /home/travis/build/angular-pouchdb/angular-pouchdb to /home/travis/.npm/angular-pouchdb/0.0.0-semantically-released/package.tgz`

(Full [Travis CI log](https://travis-ci.org/angular-pouchdb/angular-pouchdb#L212)).

I can't reproduce this error locally. Have you ran into this?

NB, angular-pouchdb has had previous releases/tags; I'm adding semantic-release at angular-pouchdb v2.0.1. Would this trigger this error?

**Comment by boennemann** [comment]
Hey @tlvince,

really cool to see you're giving semantic-release a try.
I've looked into this and currently I have no idea where it is coming from.

After the `Determining new version` there would need to be at least one other log message before the actual publishing (that might internally pack) happens. And even then, why would packing fail.

Can you try clearing caches on travis and then rerun? Unfortunately that's the only starter for debugging I can give you atm. Please report back in this issue if you have found anything.

**Comment by boennemann** [comment]
@tlvince 

I can reproduce this now, so it's definitely a semantic-release bug. Currently investigating where this is coming from, maybe a new npm version.

**Comment by boennemann** [comment]
@tlvince Okay I think I know what's happening now.
`npm publish` starts the spinner which eats up all the log output on travis.
Because of this the expected `'Nothing changed. Not publishing.'` simply isn't shown even though everything is fine.
The latest npm changed the error message a bit, so `npm ERR! addLocalDirectory Could not pack` is the expected output for an aborted `publish`. 

Can you please verify this by adding this to your `travis.yml`

```yml
before_deploy:
 - npm config set spin false --global
```

**Comment by tlvince** [comment]
Thanks for tracking that down @boennemann. I can confirm disabling the spinner gives an expected log output and this was a false alarm.

Just adding a note to the readme giving the heads up that this is normal behaviour or to disable the spinner (if npm >= v1.4.11?) would suffice.

**Comment by boennemann** [comment]
@tlvince Thanks for checking that. This started happening only with more recent npm versions.
I'll add a note once I'm back in my home wifi ;)

**Comment by gr2m** [comment]
I'd suggest to put that in the default `.travis.yml`, with a comment containing the URL of this issue.

By the way, I got bit by this issue (I think) when I tried to do the first deploy to npm. The package did not yet exist. I expected that in that case, `semantic-release` would create a 1.0.0 as a default?
