### ISSUE TITLE
Skipping a deployment with the npm provider because this branch is not permitted

### ISSUE THREAD

**Issue by gr2m** [boennemann/semantic-release#23]
I'm trying to deploy https://github.com/gr2m/couchdb-view-tester, the build looks good, but doesn't get deployed: https://travis-ci.org/gr2m/couchdb-view-tester/builds/61492518

I don't get the error message. I've set `master` as branch in `deploy.on.branch`. Anything I'm missing?

**Comment by gr2m** [comment]
oh, also, funny version on npm right now :D 
https://www.npmjs.com/package/couchdb-view-tester

**Comment by gr2m** [comment]
I've removed the bad version, but here's a screenshot 
![screen shot 2015-05-06 at 18 41 36](https://cloud.githubusercontent.com/assets/39992/7498228/9609b970-f41f-11e4-83c1-1ff549d57af1.png)

**Comment by gr2m** [comment]
It also created a version on GitHub: https://github.com/gr2m/couchdb-view-tester/releases 

I can leave that for now and delete it once things are working

**Comment by boennemann** [comment]
I guess this happens because you have a multi job setup. You need to use "travis-after-all" for this. You can copy the configuration from semantic-release itself: https://github.com/boennemann/semantic-release/blob/master/.travis.yml
