### ISSUE TITLE
First release uses version 0.0.0-semantically-released

### ISSUE THREAD

**Issue by tlvince** [boennemann/semantic-release#24]
As per https://github.com/boennemann/semantic-release/issues/18#issuecomment-99531802, if the package is new (i.e. does not pre-exist on npm), packages are published with `"version": "0.0.0-semantically-released"`. I'd expect `1.0.0` to be used here.

As a workaround, I first publish `1.0.0` manually, then add semantic-release afterwards.

**Comment by boennemann** [comment]
Thanks for the issue Tom. I couldn't reproduce this yet, there are also tests for this, but there definitely seems to be a problem, as @gr2m reports the same.

Is there anything special you're using, e.g. scoped modules? 

Maybe you can provide steps to reproduce or send me some Travis logs? :)

Sorry for the inconveniences this may have caused.

**Comment by gr2m** [comment]
I didn't do anything special on my side, besides testing with different node versions:
https://github.com/gr2m/couchdb-view-tester/blob/master/.travis.yml#L3-L5

**Comment by tlvince** [comment]
I'll prepare a reduced test case and get back to you.

**Comment by tlvince** [comment]
I tried, but couldn't reproduce this (as of semantic-release v3.3.1); https://github.com/tlvince/tlvince-semantic-release-initial-version was correctly [published](https://www.npmjs.com/package/tlvince-semantic-release-initial-version) with v1.0.0.

**Comment by boennemann** [comment]
Thanks for checking :)

**Comment by boennemann** [comment]
Also @gr2m, as noted elsewhere, you need "travis_after_all" for more than one node version :)

**Comment by tlvince** [comment]
:+1:

**Comment by gr2m** [comment]
:+1:

**Comment by stojanovic** [comment]
I managed to reproduce this 2-3 days ago - I tried to add semantic-release on module that was already v1.1.0 and it was reset to 0.0.0-semantically-released.

**Comment by boennemann** [comment]
Thanks @stojanovic,

the scenario you describe doesn't make sense to me as to why it would fail, but that doesn't mean _anything_.
I'll investigate this very soon.

**Comment by boennemann** [comment]
I couldn't reproduce and so I think this happens when something with the setup is wrong. As the setup is super bothersome and needs a lot more thought and work I've just added a new verification that aborts the release if a version that matches `/semantically-released/` is about to be published.

So while this shouldn't happen anymore the underlying problem still exists. The progress on this is tracked in other issues though. This is why closed again.

Thanks y'all
