### ISSUE TITLE
Breaking change/major release not detected

### ISSUE THREAD

**Issue by tlvince** [boennemann/semantic-release#25]
According to [conventional-changelog](https://github.com/ajoslin/conventional-changelog/blob/85cad9b4360ca8a05eafd79f0c446741d602fcb1/CONVENTIONS.md#footer):

> Breaking Changes are detected as such if the Body contains a line starting with BREAKING CHANGES: The rest of the commit message is then used for this.

[parseRawCommit](https://github.com/ajoslin/conventional-changelog/blob/3cae05244e48af9cf4abbef3114060db585a574c/lib/git.js#L70) shows they match on `BREAKING CHANGE`, i.e. ignoring the trailing **S**.

Given that, in https://github.com/eHealthAfrica/qsl.js/commit/0816bf9525b05c7489463adc59785cfefa94e13e, I have the following in my commit message:

> BREAKING CHANGE: `qsl.parse` returns a more useful formatted response, rather
than an intermediary array of objects representation.

Therefore, I would have expected semantic-release to published a major release. Instead, it published a minor. See [build log](https://travis-ci.org/eHealthAfrica/qsl.js/builds/62393652#L184).

**Comment by boennemann** [comment]
Yeah I'm sorry, this bug sneaked in when I've rewritten that part for the plugin system :/
Fixed here: https://github.com/boennemann/semantic-release/releases/tag/v3.2.2

Thanks for baring with me in this early phase :) This is _really_ appreciated!

**Comment by tlvince** [comment]
No probs. Thanks!
