### ISSUE TITLE
Integrate with dont-break

### ISSUE THREAD

**Issue by bahmutov** [boennemann/semantic-release#26]
A major problem with minor / patch releases is that they might accidentally break projects that depend on them. I have a tool dont-break https://github.com/bahmutov/dont-break that can check if your release is breaking existing users - perfect step for CI before publishing.

**Comment by boennemann** [comment]
Hey @bahmutov,

thanks for writing. You could use the verification hook, that was added in recent versions, to do this :)
Have a look here: https://github.com/boennemann/semantic-release/wiki/verification-hook

Best,
Stephan
