### ISSUE TITLE
feature request: support private npm packages

### ISSUE THREAD

**Issue by gr2m** [boennemann/semantic-release#28]
<3

**Comment by boennemann** [comment]
I'd consider it a bug at this point, because If we'd use npm directly for the requests it should just work™.
The actual problem is that testing gets even trickier, but this is high on our agenda :)

**Comment by gr2m** [comment]
![LET ME LOVE YOU](http://media.giphy.com/media/12J28qxlb4sfFm/giphy.gif)

**Comment by christophwitzko** [comment]
:revolving_hearts:
