### ISSUE TITLE
npm ERR! publish Failed PUT 500

### ISSUE THREAD

**Issue by gr2m** [boennemann/semantic-release#32]
https://travis-ci.org/gr2m/moment.parseFormat/builds/64160442#L202 – any idea?

**Comment by gr2m** [comment]
btw, it tried to publish `v0.1.0`. I'd have expected `v1.0.0`. Was that intended?

**Comment by boennemann** [comment]
`0.1.0` is expected as it just uses the previously published version to determine the new one. Only if no version is present it jumps directly to `1.0.0`.

The failed PUT looks like some problem with the npm credentials, can you double check whether they're okay? :)

**Comment by gr2m** [comment]
will do! 

Regarding jumping to `0.1.0`. As it's about semver, I'd always jump to 1.0.0 if it doesn't exist yet. Let's put all the npm packages to 1.0.0+, because below: everything can change at any time, right?

**Comment by gr2m** [comment]
for the time being, how can I force it to release 1.0.0?

**Comment by boennemann** [comment]
You can now force it to 1.0.0 by adding a breaking note to a commit message. Much like async did recently: "No known breaking changes, we are simply complying with semver from here on out."

https://github.com/caolan/async/blob/master/CHANGELOG.md

Simply releasing 1.0.0 for everything below it seems a bit harsh, and might come with some unintended side effects, so I'm leaving it out for now, but maybe we can do it in the future, when things are more stable and tested by more folks.

**Comment by gr2m** [comment]
:+1: Also, async should use semantic-release! Let's do some lobbying :D
