### ISSUE TITLE
How does semantic-release know what version (major, minor, patch) to release?

### ISSUE THREAD

**Issue by dbkaplun** [boennemann/semantic-release#35]

**Comment by dbkaplun** [comment]
I see, looks like it uses AngularJS commit message conventions to determine what version to release. This needs to be made more clear in the README.

**Comment by christophwitzko** [comment]
Hi @dbkaplun,

the [default analyzer](https://github.com/boennemann/semantic-release/blob/master/lib/analyzer.js) handles the [AngularJS commit message conventions](https://github.com/ajoslin/conventional-changelog/blob/master/CONVENTIONS.md) like this:

| commit type                                | version type |
|--------------------------------------------|--------------|
| commit message contains `BREAKING CHANGE:` | major        |
| `feat`                                     | minor        |
| `fix`                                      | patch        |

You can find the full description of the AngularJS commit message conventions in the [wiki](https://github.com/boennemann/semantic-release/wiki/commit-analysis). There is also an explanation on how to write your own commit message analyzer.

have a nice day
Christoph

**Comment by tusharmath** [comment]
The default analyzer link is broken.

**Comment by hbetts** [comment]
@tusharmath under the [analyzeCommits](https://github.com/semantic-release/semantic-release#analyzecommits) section on the README, you will see a link to the `default implementation`.
