### ISSUE TITLE
semantic-release@next

### ISSUE THREAD

**Issue by boennemann** [boennemann/semantic-release#44]
While the core principles of this module are pretty solid there are a few things that currently make it awful to use or much rather setup (because one doesn't _use_ it that much really).

## Being part of the *publish* lifecycle

The original idea of integrating semantic-release into the npm lifecycle was that it's easy to setup, because for example on Travis there are ready made deploy plugins that run `npm publish` and so it's working out of the box.
There are two reasons why this wasn't a good idea.

1. Making an integration into `prepublish` and `postpublish` work requires a lot of hacking around edge-cases, up to the point that most of the code that's currently present is for these hacks.
2. The Travis deploy integration with npm is so bad, that we need to do it ourselves anyways. Namely auth, where it still uses the old base64 encoded username and password, but also one can't pass arguments to the publish command itself.

How it could be done instead:

Have both the pre and the post step like they're now (without all the hacks) and wrap them in another npm script like `npm run semantic-release` that does nothing more than `semantic-release pre && npm publish && semantic-release post`. That'd require a slightly different Travis setup, but that could be generated anyways. See next point.

A list of hacks that would go away:
1. Having a placeholder version in the package.json
2. `npm publish`-ception, where it runs `npm publish` inside `npm prepublish`. No more error, even though it's been successful.
3. Parsing npmArgv to check if it really runs inside `prepublish` rather than `link`, `pack` or `install`.

## The setup is **horrifying**

The ideal would be one setup wizard where you enter nothing more than github username and password
and it works. Both npm and travis auth is taken from the environment, but you can still enter your passwords and usernames if you want to have separate tokens.

That could mainly be accomplished by building an `.npmrc` with the right auth token that's taken from a secure environment variable. Both `GH_TOKEN` and `NPM_TOKEN` should be encrypted using the Travis API for that, rather than putting it in the `.travis.yml`.

## Bloat

I tried to keep the setup wizard basic, because all the packages would be installed every single time (parsing yml, interactivity etc). I'd like to have a semantic-release cli that can be as bloated as we want, because it simply installs a really lean core that's the only thing that packages actually depend upon and install.

## Tests

Stop using sinopia, spin up a real registry and basically use the same testing setup the npm cli itself uses. Write unit tests.

<hr>

I want to get these things done, before adding new features, because it will make the entire project so much more maintainable and fun to work with.

**Comment by boennemann** [comment]
Pinging a few people that I think could be interested (also feedback would be cool :))
@christophwitzko @janl @gr2m @othiym23 @rmehner @remy @tlvince

**Comment by rmehner** [comment]
> The Travis deploy integration with npm is so bad, that we need to do it ourselves anyways. Namely auth, where it still uses the old base64 encoded username and password, but also one can't pass arguments to the publish command itself.

I'm a bit undecided on that. My first thought about this was: Why not fix the npm integration of Travis so that all other unrelated projects can benefit from that? I know that Travis is essentially a product that we'd improve there, but they're good citizens and so is npm inc. You know better than I do what's wrong with the integration, but happy to discuss that and help out with some my Ruby skills if needed.

**Comment by gr2m** [comment]
I had the same thought as @rmehner: any chance we could help fix travis instead? Or is it a conceptual issue?

**Comment by boennemann** [comment]
@rmehner @gr2m This sounded way to bold. Doing it on our own essentially means setting an encrypted env var with the npm token, creating an `~/.npmrc` and running `npm publish` on `after_success`. (npm@^2.0.0 required)

The `~/.npmrc`
```
registry=https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```

I want to build this for semantic-release first, so there are no blockers. I am more than happy to bring this back to Travis then. (Same goes for the npm team, as they want to get rid of the old token). The dpl tool is open source anyway: https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/npm.rb

**Comment by janl** [comment]
I’m generally +1 on all of this :)
