### ISSUE TITLE
You cannot publish over the previously published version 1.0.0

### ISSUE THREAD

**Issue by gr2m** [boennemann/semantic-release#45]
is this expected behavior? 
https://travis-ci.org/hoodiehq/pouchdb-hoodie-sync/jobs/67034467#L364

I don't understand why it tries to deploy at all. There were only `chore: ...` commits since 1.0.0 was released?

**Comment by boennemann** [comment]
At first sight this seems like a setup issue for me. If the request to the registry fails it assumes version 1.0.0, which is why it worked for the first time, but not now, for the second time. I'll try and figure out where the problem ist.

**Comment by boennemann** [comment]
Okay I've looked into it now and it seems like the npm credentials aren't setup correctly. Can you try doing the setup again there?

(Sooooorrrrryyy, a solution is in sight: github.com/semantic-release/core)
