### ISSUE TITLE
Empty value for parameter 'owner': undefined undefined

### ISSUE THREAD

**Issue by gr2m** [boennemann/semantic-release#48]
I've run into this before, and I think you said it happens randomly and it will be fixed with next semantic-release, but here it is for reference:
https://travis-ci.org/eHealthAfrica/joffrey-bootstrap/builds/71077848#L144

If, by chance, you know how to aovid /  workaround / fix this, please enlighten me :bulb:

**Comment by boennemann** [comment]
The repo url in your package.json is malformed: https://github.com/eHealthAfrica/joffrey-bootstrap/blob/master/package.json#L13

Use one of the supported formats by npm/the used parser: https://www.npmjs.com/package/parse-github-repo-url

I will add a step that not only checks for presence, but the right url format to semantic-release@next

**Comment by gr2m** [comment]
oh wow, note that I did not set this property, it was the default that npm suggested on setup

**Comment by boennemann** [comment]
What npm version are you running on? They always look this for me: `git+https://github.com/semantic-release/core.git`

**Comment by gr2m** [comment]
forget what I said, that was one of 7 repos I did all at once, but this one I think I copy / pasted from an existing one and only find/replaced stuff in package.json. Thanks for the help, sorry for the noise

**Comment by boennemann** [comment]
No noise, I could add a very helpful error message just because of this :+1:
